### ISSUE TITLE
Confirm about platform independent builds

### ISSUE THREAD

**Issue by skellock** [skellock/typescript-with-electron-react-kit#91]
I know that on a mac, you can cut production builds for linux & windows.

@rmevans9 wants to know... can you do the same on Windows & Linux too?

**Comment by rmevans9** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by rmevans9** [comment]
looks like in typical Apple fashion you can only build a macOS build on a macOS (or on a build server it seems)

**Comment by skellock** [comment]
![giphy](https://user-images.githubusercontent.com/68273/29299041-f0da1db4-8139-11e7-82bd-d354a38cba5d.gif)
